### ISSUE TITLE
Unable to validate published API using openapi-cli lint

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#112]
When I try to validate any OGC API - Processes, I face the following error:

```
[1] https:/raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/outputInfo.yaml:11:5 at #/properties/format

Can't resolve $ref

 9 |   $ref: "valueType.yaml"
10 | format:
11 |   $ref: "#/components/schemas/format"
12 |

Error was generated by the no-unresolved-refs rule.
```

This pull request #111 should solve the issue by using the format.yaml file as reference.

Note that this should also solve the issue with redoc ([link](https://opengeospatial.github.io/architecture-dwg/api-processes/index.html) from the OGC API - Processes [official page](https://ogcapi.ogc.org/processes/)), which returns the same kind of information as shown bellow:

```
SyntaxError: Error resolving $ref pointer "https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/outputInfo.yaml#/components/schemas/format". 
Token "components" does not exist.
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28049)
    at u.resolve (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:94556)
    at o.resolve (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:81461)
    at a._resolve (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:49055)
    at s (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:51575)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:51457
    at Array.forEach (<anonymous>)
    at a (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:51378)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:51476
    at Array.forEach (<anonymous>)
```

**Comment by bpross-52n** [comment]
Pull Request #111 was merged, so this should be fixed. Thanks!
